# Generated by Django 5.0.7 on 2024-07-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='media/profile_picture')),
                ('professional_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField()),
                ('projects_finished', models.IntegerField()),
                ('courses_completed', models.IntegerField()),
                ('workshops_attented', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_in', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('cgpa', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('uploaded_image', models.ImageField(upload_to='media/certificates')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
    ]
