# Generated by Django 5.0.7 on 2024-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='resume',
            field=models.FileField(null=True, upload_to='media/resume'),
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
