# Generated by Django 5.0.7 on 2024-07-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personaldetails_resume_projects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('github', models.CharField(max_length=300)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personaldetails')),
            ],
        ),
    ]
